apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: analytics
type: Opaque
data:
  AWS_DYNAMODB_TABLE: "XXXXXXXXXXXXXX"
  AWS_REGION: "XXXXXXXXXXXXXX"
  AWS_SQS_URL: "XXXXXXXXXXXXXX"
