apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: analytics
type: Opaque
data:
  AWS_DYNAMODB_TABLE: "YW5hbHl0aWNzLWV2ZW50cw=="
  AWS_REGION: "dXMtZWFzdC0x"
  AWS_SQS_URL: "aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vODE3ODc4NTI5MzA2L2FuYWx5dGljcy1xdWV1ZQ=="
