apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth
type: Opaque
data:
  DATABASE_URL: "XXXXXXXXXXXXXX"
  DB_USER: "XXXXXXXXXXXXXX"
  DB_PASSWORD: "XXXXXXXXXXXXXX"
  MASTER_KEY: "XXXXXXXXXXXXXX"