apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth
type: Opaque
data:
  DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzMTIzQGRiLWF1dGgtaW5zdGFuY2UtMS5jbzFxMDJtcWc1N2MudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvYXV0aF9kYg=="
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXMxMjM="
  MASTER_KEY: "bWluaGEtY2hhdmUtdWx0cmEtc2VjcmV0YS0yMDI2"