apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: evaluation
type: Opaque
data:
  SQS_QUEUE_URL: "Y2x1c3RlcmNmZy50b2dnbGVtYXN0ZXItcmVkaXMucmtudTI2LnVzZTEuY2FjaGUuYW1hem9uYXdzLmNvbQ=="
  REDIS_URL: cmVkaXM6Ly9jbHVzdGVyY2ZnLnRvZ2dsZW1hc3Rlci1yZWRpcy5ya251MjYudXNlMS5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk=