apiVersion: v1
kind: Secret
metadata:
  name: flag-secrets
  namespace: flag
type: Opaque
data:
  DATABASE_URL: "cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3JlczEyM0BkYi1mbGFnLWluc3RhbmNlLTEuY28xcTAybXFnNTdjLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2ZsYWdfZGI="
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXMxMjM="
  MASTER_KEY: "bWluaGEtY2hhdmUtdWx0cmEtc2VjcmV0YS0yMDI2"