apiVersion: v1
kind: Secret
metadata:
  name: flag-secrets
  namespace: flag
type: Opaque
data:
  DATABASE_URL: "XXXXXXXXXXXXXX"
  DB_USER: "XXXXXXXXXXXXXX"
  DB_PASSWORD: "XXXXXXXXXXXXXX"
  MASTER_KEY: "XXXXXXXXXXXXXX"