apiVersion: v1
kind: Secret
metadata:
  name: targeting-secrets
  namespace: targeting
type: Opaque
data:
  DATABASE_URL: "cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3JlczEyM0BkYi10YXJnZXRpbmctaW5zdGFuY2UtMS5jbzFxMDJtcWc1N2MudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvdGFyZ2V0aW5nX2Ri"
  MASTER_KEY: "bWluaGEtY2hhdmUtdWx0cmEtc2VjcmV0YS0yMDI2"