apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: flag
---
apiVersion: v1
kind: Namespace
metadata:
  name: targeting
---
apiVersion: v1
kind: Namespace
metadata:
  name: evaluation
---
apiVersion: v1
kind: Namespace
metadata:
  name: analytics
