apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-config
  namespace: evaluation
data:
  APP_PORT: "8004"
  AUTH_SERVICE_URL: "http://auth-service.auth:8001"
  FLAG_SERVICE_URL: "http://flag-service.flag:8002"
  TARGETING_SERVICE_URL: "http://targeting-service.targeting:8003"
