apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: evaluation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: 817878529306.dkr.ecr.us-east-1.amazonaws.com/togglemaster/evaluation-service:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 8004

          envFrom:
            - configMapRef:
                name: evaluation-config
            - secretRef:
                name: evaluation-secrets

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            tcpSocket:
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8004
            initialDelaySeconds: 20
            periodSeconds: 20
