apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: targeting
spec:
  type: ClusterIP
  selector:
    app: targeting-service
  ports:
    - port: 8003
      targetPort: 8003
